### ISSUE TITLE
Wintermute DLC error

### ISSUE THREAD

**Issue by IIReDeeMeRII** [Xpazeman/tld-weight-tweaks#6]
[21:12:52.159] [Il2CppAssemblyGenerator] Error Generating Interop Assemblies!
System.NullReferenceException: Object reference not set to an instance of an object.
   at Il2CppInterop.Generator.Contexts.AssemblyRewriteContext.RewriteTypeRef(TypeReference typeRef) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Contexts/AssemblyRewriteContext.cs:line 133
   at Il2CppInterop.Generator.Contexts.AssemblyRewriteContext.RewriteTypeRef(TypeReference typeRef) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Contexts/AssemblyRewriteContext.cs:line 108
   at Il2CppInterop.Generator.Passes.Pass12FillTypedefs.DoPass(RewriteGlobalContext context) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Passes/Pass12FillTypedefs.cs:line 33
   at Il2CppInterop.Generator.Runners.InteropAssemblyGeneratorRunner.Run(GeneratorOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Runners/InteropAssemblyGenerator.cs:line 79
   at Il2CppInterop.Generator.Il2CppInteropGenerator.Start() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Il2CppInteropGenerator.cs:line 30
   at Il2CppInterop.Generator.Il2CppInteropGenerator.Run() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Il2CppInteropGenerator.cs:line 47
   at MelonLoader.Il2CppAssemblyGenerator.Packages.Il2CppInterop.ExecuteInterop() in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Packages\Il2CppInterop.cs:line 97
[NewEntryPoint] Starting.

[21:12:52.198] Loading Mods from 'D:\SteamLibrary\steamapps\common\TheLongDark\tld_dlc\wintermute\Mods'...
[21:12:52.200] ------------------------------
[21:12:52.208] Melon Assembly loaded: '.\Mods\ModSettings.dll'
[21:12:52.209] SHA256 Hash: '50c4594048ade6676a3aa5c7d278a2d8a82f4ed3f489b6aeba01acd4396e59fe'
[21:12:52.214] Melon Assembly loaded: '.\Mods\WeightTweaks.dll'
[21:12:52.215] SHA256 Hash: '0f1c2040191048e1abe040e23c43f78b41b8896477562a44edefe81b6a1a2567'

[21:12:52.795] ------------------------------
[21:12:52.796] ModSettings v1.9.0
[21:12:52.796] by zeobviouslyfakeacc
[21:12:52.798] Assembly: ModSettings.dll
[21:12:52.798] ------------------------------
[21:12:52.806] ------------------------------
[21:12:52.806] WeightTweaks v2.2.0
[21:12:52.806] by Xpazeman
[21:12:52.807] Assembly: WeightTweaks.dll
[21:12:52.808] ------------------------------
[21:12:52.808] ------------------------------
[21:12:52.809] 2 Mods loaded.

[21:12:54.129] Class::Init signatures have been exhausted, using a substitute!
[21:12:54.177] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain[21:12:54.219] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[21:12:54.222] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[21:12:54.232] Support Module Loaded: D:\SteamLibrary\steamapps\common\TheLongDark\tld_dlc\wintermute\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[21:12:54.240] Registered mono type ModSettings.ModSettingsGUI in il2cpp domain
[21:12:54.708] [WeightTweaks] HarmonyLib.HarmonyException: Patching exception in method null
 ---> System.ArgumentException: Undefined target method for patch method static void WeightTweaks.GearItem_GetItemWeightKG::Postfix(Il2Cpp.GearItem __instance, Single& __result)
   at HarmonyLib.PatchClassProcessor.PatchWithAttributes(MethodBase& lastOriginal)
   at HarmonyLib.PatchClassProcessor.Patch()
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.Harmony.<PatchAll>b__11_0(Type type)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.Harmony.PatchAll(Assembly assembly)
   at MelonLoader.MelonMod.HarmonyInit() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonMod.cs:line 40
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
Setting breakpad minidump AppID = 305620
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198077109819 [API loaded no]
[21:13:04.868] Building Mod Settings GUI
[21:13:04.910] [ModSettings] Exception while building Mod Settings GUI
System.TypeInitializationException: The type initializer for 'ModSettings.ChoiceAttribute' threw an exception.
 ---> System.TypeLoadException: Could not load type 'Il2CppTLD.Gameplay.Tunable.CustomTunableDayNightMultiplier' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ModSettings.ChoiceAttribute..cctor()
   --- End of inner exception stack trace ---
   at ModSettings.GUIBuilder.AddSettings(ModSettingsBase modSettings) in C:\Users\Jeremy\source\repos\ModSettings\GUI\GUIBuilder.cs:line 46
   at ModSettings.ModSettingsGUIBuilder.AddSettings(ModSettingsBase modSettings) in C:\Users\Jeremy\source\repos\ModSettings\GUI\ModSettingsGUIBuilder.cs:line 38
   at ModSettings.ModSettingsMenu.BuildGUI(Panel_OptionsMenu panel) in C:\Users\Jeremy\source\repos\ModSettings\ModSettingsMenu.cs:line 43
   at ModSettings.ModSettingsPatches.BuildModSettingsGUIPatch.Postfix(Panel_OptionsMenu __instance) in C:\Users\Jeremy\source\repos\ModSettings\GUI\ModSettingsPatches.cs:line 21
[21:13:18.377] Registered mono type ModSettings.SliderFixPatches+SliderBarDepthFixer in il2cpp domain

**Comment by Xpazeman** [comment]
Wintermute currently doesn't support mods made for survival
